package okf

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

func GenerateBundleIndex(concepts []*Concept, baseDir string) error {
	indexPath := filepath.Join(baseDir, "index.md")

	sort.Slice(concepts, func(i, j int) bool {
		return concepts[i].ID < concepts[j].ID
	})

	var content strings.Builder

	content.WriteString("# Knowledge Bundle Index\n\n")
	content.WriteString("> Automatically generated by OKF Engine v0.2\n\n")
	content.WriteString("| Concept ID | Type | Title | Trust Tier | Status |\n")
	content.WriteString("| :--- | :--- | :--- | :--- | :--- |\n")

	for _, c := range concepts {
		title := c.Frontmatter.Title
		if title == "" {
			title = c.ID
		}
		status := c.Frontmatter.Status
		if status == "" {
			status = "draft"
		}
		fmt.Fprintf(&content, "| [`%s`](/%s.md) | `%s` | %s | **%s** | `%s` |\n",
			c.ID, c.ID, c.Frontmatter.Type, title, c.TrustTier, c.Frontmatter.Status,
		)
	}

	return os.WriteFile(indexPath, []byte(content.String()), 0644)
}

func AppendLogEntry(baseDir string, actor Actor, action string, conceptID string, summary string) error {
	logPath := filepath.Join(baseDir, "log.md")

	if _, err := os.Stat(logPath); os.IsNotExist(err) {
		header := "# Knowledge Bundle Audit Log\n\nChronological record of concept creations, updates, and verifications.\n\n"
		_ = os.WriteFile(logPath, []byte(header), 0644)
	}

	f, err := os.OpenFile(logPath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	timepstamp := time.Now().Format(time.RFC3339)
	entry := fmt.Sprintf("- **%s** [%s] `%s` by `%s`: %s\n",
		timepstamp, action, conceptID, actor, summary)

	_, err = f.WriteString(entry)
	return err
}
